import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Trello 2.0',
  description: 'Generated by Fox Dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
